export const READ_DEPARTMENT = "READ_DEPARTMENT";
export const INSERT_DEPARTMENT = "INSERT_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";